#Requires AutoHotkey v2.0

delay := 6000
commandList := [
    ;// Cursor movement
    ["move cursor left","h"],
    ["move cursor down","j"],
    ["move cursor up","k"],
    ["move cursor right","l"],
    ["move cursor down (multi-line text)","gj"],
    ["move cursor up (multi-line text)","gk"],
    ["move to top of screen","H"],
    ["move to middle of screen","M"],
    ["move to bottom of screen","L"],
    ["jump forwards to the start of a word","w"],
    ["jump forwards to the start of a word (words can contain punctuation)","W"],
    ["jump forwards to the end of a word","e"],
    ["jump forwards to the end of a word (words can contain punctuation)","E"],
    ["jump backwards to the start of a word","b"],
    ["jump backwards to the start of a word (words can contain punctuation)","B"],
    ["jump backwards to the end of a word","ge"],
    ["jump backwards to the end of a word (words can contain punctuation)","gE"],
    ["move cursor to matching character","%"],
    ["jump to the start of the line","0"],
    ["jump to the first non-blank character of the line","^"],
    ["jump to the end of the line","$"],
    ["jump to the last non-blank character of the line","g_"],
    ["go to the first line of the document","gg"],
    ["go to the last line of the document","G"],
    ["go to line 5","5gg"],
    ["go to line 5","5G"],
    ["move to local declaration","gd"],
    ["move to global declaration","gD"],
    ["jump to next occurrence of character x","fx"],
    ["jump to before next occurrence of character x","tx"],
    ["jump to the previous occurrence of character x","Fx"],
    ["jump to after previous occurrence of character x","Tx"],
    ["repeat previous f, t, F or T movement",";"],
    ["repeat previous f, t, F or T movement backwards",","],
    ["jump to next paragraph or block","}"],
    ["jump to previous paragraph or block","{"],
    ["center cursor on screen","zz"],
    ["position cursor on top of the screen","zt"],
    ["position cursor on bottom of the screen","zb"],
    ["move screen down one line without moving cursor","Ctrl+e"],
    ["move screen up one line without moving cursor","Ctrl+y"],
    ["move screen up one page","Ctrl+b"],
    ["move screen down one page","Ctrl+f"],
    ["move cursor and screen down half a page","Ctrl+d"],
    ["move cursor and screen up half a page","Ctrl+u"],

    ;// Insert mode
    ["insert before the cursor","i"],
    ["insert at the beginning of the line","I"],
    ["insert (append) after the cursor","a"],
    ["insert (append) at the end of the line","A"],
    ["open new line below current line","o"],
    ["open new line above current line","O"],
    ["append at end of word","ea"],
    ["delete character before cursor (insert mode)","Ctrl+h"],
    ["delete word before cursor (insert mode)","Ctrl+w"],
    ["add line break at cursor position (insert mode)","Ctrl+j"],
    ["indent line one shiftwidth (insert mode)","Ctrl+t"],
    ["de-indent line one shiftwidth (insert mode)","Ctrl+d"],
    ["auto-complete next match before cursor (insert mode)","Ctrl+n"],
    ["auto-complete previous match before cursor (insert mode)","Ctrl+p"],
    ["insert contents of register x (insert mode)","Ctrl+rx"],
    ["temporarily enter normal mode for one command","Ctrl+ox"],
    ["exit insert mode","Esc"],
    ["exit insert mode","Ctrl+c"],

    ;// Editing
    ["replace a single character","r"],
    ["replace characters until Esc","R"],
    ["join line below with space","J"],
    ["join line below without space","gJ"],
    ["reflow paragraph","gwip"],
    ["switch case up to motion","g~"],
    ["change to lowercase up to motion","gu"],
    ["change to uppercase up to motion","gU"],
    ["change entire line","cc"],
    ["change to end of line","c$"],
    ["change to end of line","C"],
    ["change entire word","ciw"],
    ["change to end of word","cw"],
    ["change to end of word","ce"],
    ["delete char and insert text","s"],
    ["delete line and insert text","S"],
    ["transpose two letters","xp"],
    ["undo","u"],
    ["restore last changed line","U"],
    ["redo","Ctrl+r"],
    ["repeat last command","."],

    ;// Visual mode
    ["start visual mode","v"],
    ["start linewise visual mode","V"],
    ["move to other end of marked area","o"],
    ["start visual block mode","Ctrl+v"],
    ["move to other corner of block","O"],
    ["mark a word","aw"],
    ["mark block with ()","ab"],
    ["mark block with {}","aB"],
    ["mark block with <> tags","at"],
    ["inner block with ()","ib"],
    ["inner block with {}","iB"],
    ["inner block with <> tags","it"],
    ["exit visual mode","Esc"],
    ["exit visual mode","Ctrl+c"],

    ;// Visual commands
    ["shift text right",">"],
    ["shift text left","<"],
    ["yank marked text","y"],
    ["delete marked text","d"],
    ["switch case","~"],
    ["change marked text to lowercase","u"],
    ["change marked text to uppercase","U"],

    ;// Registers
    ["show registers content",":reg"],
    ["yank into register x",'\"xy'],
    ["paste from register x",'\"xp'],
    ["yank into system clipboard","+y"],
    ["paste from system clipboard","+p"],

    ;// Marks
    ["list marks",":marks"],
    ["set mark a","ma"],
    ["jump to mark a","``a"],
    ["yank to mark a","y``a"],
    ["go to last exit position","``0"],
    ["go to last edit position",'``\"'],
    ["go to last change position","``."],
    ["go to before last jump","``"],
    ["list jumps",":jumps"],
    ["go to newer jump","Ctrl+i"],
    ["go to older jump","Ctrl+o"],
    ["list changes",":changes"],
    ["go to newer change","g,"],
    ["go to older change","g;"],
    ["jump to tag under cursor","Ctrl+]"],

    ;// Macros
    ["record macro a","qa"],
    ["stop recording macro","q"],
    ["run macro a","@a"],
    ["rerun last macro","@@"],

    ;// Cut and paste
    ["yank a line","yy"],
    ["yank 2 lines","2yy"],
    ["yank from cursor to next word","yw"],
    ["yank word under cursor","yiw"],
    ["yank word under cursor and space","yaw"],
    ["yank to end of line","y$"],
    ["yank to end of line","Y"],
    ["paste after cursor","p"],
    ["paste before cursor","P"],
    ["paste after cursor and move cursor after","gp"],
    ["paste before cursor and move cursor after","gP"],
    ["delete a line","dd"],
    ["delete 2 lines","2dd"],
    ["delete from cursor to next word","dw"],
    ["delete word under cursor","diw"],
    ["delete word under cursor and space","daw"],
    ["delete lines 3 to 5",":3,5d"],
    ["delete from current to end of file",":.,$d"],
    ["delete from current to beginning of file",":.,1d"],
    ["delete from line 10 to beginning",":10,1d"],
    ["delete lines matching pattern",":g/{pattern}/d"],
    ["delete lines not matching pattern",":g!/{pattern}/d"],
    ["delete to end of line","d$"],
    ["delete to end of line","D"],
    ["delete character","x"],

    ;// Indent text
    ["indent one shiftwidth",">>"],
    ["de-indent one shiftwidth","<<"],
    ["indent block on brace",">%"],
    ["de-indent block on brace","<%"],
    ["indent inner block with ()",">ib"],
    ["indent block with <> tags",">at"],
    ["re-indent 3 lines","3=="],
    ["re-indent block on brace","=%"],
    ["re-indent inner block with {}","=iB"],
    ["re-indent entire buffer","gg=G"],
    ["paste and adjust indent","]p"],

    ;// Exiting
    ["write file"," :w"],
    ["write file as sudo",":w !sudo tee %"],
    ["write and quit",":wq"],
    ["write and quit",":x"],
    ["write and quit","ZZ"],
    ["quit",":q"],
    ["quit without saving",":q!"],
    ["quit without saving","ZQ"],
    ["write and quit all",":wqa"],

    ;// Search and replace
    ["search forward for pattern","/pattern"],
    ["search backward for pattern","?pattern"],
    ["very magic regex search","\\vpattern"],
    ["repeat search forward","n"],
    ["repeat search backward","N"],
    ["replace all in file",":%s/old/new/g"],
    ["replace all in file with confirm",":%s/old/new/gc"],
    ["remove search highlight",":noh"],

    ;// Search in multiple files
    ["search in multiple files",":vim /pattern/ {file}"],
    ["next search match",":cn"],
    ["previous search match",":cp"],
    ["open quickfix list",":cope"],
    ["close quickfix list",":ccl"],

    ;// Tabs
    ["open file in new tab",":tabnew"],
    ["open file in new tab",":tabnew {file}"],
    ["move split to new tab","Ctrl+wT"],
    ["next tab","gt"],
    ["next tab",":tabn"],
    ["previous tab","gT"],
    ["previous tab",":tabp"],
    ["go to tab number #","#gt"],
    ["move current tab to position #",":tabm #"],
    ["close current tab",":tabc"],
    ["close all other tabs",":tabo"],
    ["run command on all tabs",":tabdo {command}"],

    ;// Multiple files & windows
    ["edit file",":e {file}"],
    ["next buffer",":bn"],
    ["previous buffer",":bp"],
    ["delete buffer",":bd"],
    ["go to buffer by index",":b#"],
    ["go to buffer by name",":b {file}"],
    ["list buffers",":ls"],
    ["list buffers",":buffers"],
    ["split window with file",":sp {file}"],
    ["vertical split window with file",":vs {file}"],
    ["edit all buffers as vertical windows",":vert ball"],
    ["edit all buffers as tabs",":tab ball"],
    ["split window","Ctrl+ws"],
    ["split window vertically","Ctrl+wv"],
    ["switch windows","Ctrl+ww"],
    ["quit window","Ctrl+wq"],
    ["exchange windows","Ctrl+wx"],
    ["equalize window sizes","Ctrl+w="],
    ["move to left window","Ctrl+wh"],
    ["move to right window","Ctrl+wl"],
    ["move to window below","Ctrl+wj"],
    ["move to window above","Ctrl+wk"],
    ["make current window full height at far left","Ctrl+wH"],
    ["make current window full height at far right","Ctrl+wL"],
    ["make current window full width at bottom","Ctrl+wJ"],
    ["make current window full width at top","Ctrl+wK"]
]

rdmVimCommand(){
    instruction := Random(225)
    ToolTip(commandList[instruction][1],1355, 250, 1)
    Sleep(delay)
    ToolTip(commandList[instruction][2],1355, 270, 2)
}



loop {
    rdmVimCommand()
    sleep(delay)
}